In [1]:
import pandas as pd
import numpy as np
import openpyxl

In [2]:
zakladki = pd.read_excel('Lista uczniów SP_LO_2022_2023 propozycje ocen rocznych.xlsx', sheet_name=None).keys()
zakladki

dict_keys(['1 SP uzup', '1 SP ram', '2 SP uzup', '2 SP ram', '3 SP uzup', '3 SP ram', '4 SP ram', '4 SP uzup', '5 SP uzup', '5 SP ram', '6 SP ram', '6 SP uzup', '7 SP uzup', '8 SP uzup', '7 SP ram', '8 SP ram', '1 LO uzup', '1 LO ram', '2 LO ram', '2 LO uzup', '3 LO uzup', '3 LO ram', '4 LO uzup', 'Arkusz1'])

In [3]:
zakladki = ['1 SP uzup', '1 SP ram', '2 SP uzup', '2 SP ram', '3 SP uzup', '3 SP ram', '4 SP ram', '4 SP uzup', '5 SP uzup', '5 SP ram', '6 SP ram', '6 SP uzup', '7 SP uzup', '8 SP uzup', '7 SP ram', '8 SP ram', '1 LO uzup', '1 LO ram', '2 LO ram', '2 LO uzup', '3 LO uzup', '3 LO ram', '4 LO uzup']
zakladki.sort()
# zakladki

In [35]:
df = pd.concat(pd.read_excel('Lista uczniów SP_LO_2022_2023 propozycje ocen rocznych.xlsx', sheet_name=s, usecols='B:E', skiprows=1).assign(Klasa = s) for s in zakladki)

In [36]:
df.columns

Index(['L.p.', 'Nazwisko ucznia', 'Imię/Imiona', 'e-mail', 'Klasa'], dtype='object')

In [37]:
df.dropna(subset=['L.p.', 'Nazwisko ucznia'], inplace = True)

In [38]:
df.drop_duplicates(subset=['Nazwisko ucznia', 'Imię/Imiona','Klasa'])
df

,L.p.,Nazwisko ucznia,Imię/Imiona,e-mail,Klasa
1,1.0,Bembnista,Dawid,jolbem1978@gmail.com tombem30@wp.pl,1 LO ram
2,2.0,Bryliński,Bogdan,contact@olgabrylinska.com,1 LO ram
3,3.0,Chicińska-Ryster,Nikola,izabela2169@wp.pl,1 LO ram
4,4.0,Ciźla,Nadia,cpn.fit@gmail.com,1 LO ram
5,5.0,Czarnocka,Nikoletta,tamara.c@wp.pl,1 LO ram
...,...,...,...,...,...
91,91.0,Łapicz-Biedź,Zachary Oliver,wbiedz@gmail.com,8 SP uzup
92,92.0,Łoboz,Julia Danuta,gwiazdap@op.pl,8 SP uzup
93,93.0,Śladewski,Antoni,jacek.sladewski@msz.gov.pl,8 SP uzup
94,94.0,Żukrowska,Anastazja Apolonia,k.a.zukrowska@gmail.com,8 SP uzup
95,95.0,Lenkiewicz,Zuzanna,anka_jak@yahoo.com,8 SP uzup

In [39]:
df.loc[df['Klasa']=='3 SP ram']

,L.p.,Nazwisko ucznia,Imię/Imiona,e-mail,Klasa
1,1.0,Abouzeid,Laila,abouzeidagata@wp.pl,3 SP ram
2,2.0,Barrau-Kamińska,Ewa,aniaannakaminska@outlook.com,3 SP ram
3,3.0,Bryliński,Aleksander,contact@olgabrylinska.com,3 SP ram
4,4.0,Błażejczyk,Cyprian,blazejczykmalgorzata1@gmail.com,3 SP ram
5,5.0,Ciarciński,Franciszek,szmery80@gmail.com,3 SP ram
6,6.0,Dawidowski,Kuba,bd@sailoceans.com,3 SP ram
7,7.0,Farrell,Daniel,anna.farrell2011@gmail.com,3 SP ram
8,8.0,Głogowski,Marcel,kasia.zub@wp.pl,3 SP ram
9,9.0,Harbi,Adam,Izabela_fharbi@wp.pl,3 SP ram
10,10.0,Heugh,Daniella,ewa.heugh@gmail.com,3 SP ram
11,11.0,Juszczyk,Julia,kassjuszczyk@gmail.com,3 SP ram
12,12.0,Kalota,Leonard,judyta.kalota@gmail.com,3 SP ram
13,13.0,Kisiel,Apolonia,magda.blasiak@wp.pl,3 SP ram
14,14.0,Kucharska,Julia,magdalapszys@wp.pl,3 SP ram
15,15.0,Kula,Sylwia,marta.wysocka.3d@gmail.com,3 SP ram
16,16.0,Magdziarz,Jan,i.magdziarz@wp.pl,3 SP ram
17,17.0,Masalski,Krystian,masalski1@wp.pl,3 SP ram
18,18.0,Matuszczak,Gabriel,izabelamaria@gmail.com,3 SP ram
19,19.0,Misztal Alvarez,Nadia,jmisztal01@gmail.com,3 SP ram
20,20.0,Mudlaff,Aleksandra,teresa.mudlaff@gmail.com,3 SP ram
21,21.0,Murzanski,Cody,murzanskifamily@gmail.com,3 SP ram
22,22.0,Nowakowska,Joanna,nowakowska.k@op.pl,3 SP ram
23,23.0,Pac,Nadia,sholka999@wp.pl,3 SP ram
24,24.0,Piasecki,Filip,losmagda@wp.pl,3 SP ram
25,25.0,Planas Majchrzak,Victor,klaudiab201@gmail.com,3 SP ram
26,26.0,Polewski,Bartek,justyna.jarzembinska@wp.pl,3 SP ram
27,27.0,Rybicki,Stanisław,flightcrew17@gmail.com,3 SP ram
28,28.0,Safonov,Georgy,jmetelitsa@gmail.com,3 SP ram
29,29.0,Salwach,Tulasi,salwachola@gmail.com,3 SP ram
30,30.0,Sylla,Fode,sylla.jack5@gmail.com,3 SP ram
31,31.0,Tybuś,Natalia,etybus@gmail.com,3 SP ram
32,32.0,Zaky,Adam,bbecia@yahoo.co.uk,3 SP ram
33,33.0,Szałapska,Nel,kwiatilo@wp.pl,3 SP ram

In [40]:
dbzakladki = pd.read_excel('Uczniowie KNO 2022-2023 - aktualna — kopia.xlsx', sheet_name=None).keys()

In [41]:
dbzakladki= list(dbzakladki)
dbzakladki.sort()
dbzakladki

['1 LO ram',
 '1 LO uzup',
 '1 sp ram',
 '1 sp uzup',
 '2 LO ram',
 '2 LO uzup',
 '2 sp ram',
 '2 sp uzup',
 '3 LO ram',
 '3 LO uzup',
 '3 sp ram',
 '3 sp uzup',
 '4 LO ram',
 '4 LO uzup',
 '4 sp ram',
 '4 sp uzup',
 '5 sp ram',
 '5 sp uzup',
 '6 sp ram',
 '6 sp uzup',
 '7 sp ram',
 '7 sp uzup',
 '8 sp ram',
 '8 sp uzup',
 'Arkusz1',
 'Arkusz2',
 'Podsumowanie',
 'Teams uczniowie ALL',
 'Zespoły w Teams']

In [42]:
dbzakladki = ['1 LO ram',
 '1 LO uzup',
 '1 sp ram',
 '1 sp uzup',
 '2 LO ram',
 '2 LO uzup',
 '2 sp ram',
 '2 sp uzup',
 '3 LO ram',
 '3 LO uzup',
 '3 sp ram',
 '3 sp uzup',
 '4 LO ram',
 '4 LO uzup',
 '4 sp ram',
 '4 sp uzup',
 '5 sp ram',
 '5 sp uzup',
 '6 sp ram',
 '6 sp uzup',
 '7 sp ram',
 '7 sp uzup',
 '8 sp ram',
 '8 sp uzup']

In [55]:
db = pd.concat(pd.read_excel('Uczniowie KNO 2022-2023 - aktualna — kopia.xlsx', usecols='A:L', sheet_name = s).assign(Klasa = s) for s in dbzakladki)

In [56]:
db.columns

Index(['L.p.', 'Nazwisko ucznia', 'Imię ucznia', 'Drugie imię ucznia',
       'nr ksiegi', 'Data urodzenia ucznia', 'Miejsce urodzen..',
       'PESEL ucznia', 'Inny dokument t..', 'Nr i seria doku..',
       'Kraj pobytu ucznia', 'Email', 'Klasa'],
      dtype='object')

In [57]:
db

,L.p.,Nazwisko ucznia,Imię ucznia,Drugie imię ucznia,nr ksiegi,Data urodzenia ucznia,Miejsce urodzen..,PESEL ucznia,Inny dokument t..,Nr i seria doku..,Kraj pobytu ucznia,Email,Klasa
0,1,Staśkiewicz,Anna,Magdalena,4149,2007-12-07 00:00:00,Piła,7320704782,NaN,NaN,Niemcy,alinastaskiewicz@o2.pl,1 LO ram
1,2,Chicińska-Ryster,Nikola,Żaneta,4150,2008-04-14 00:00:00,CHESTERFIELD ENGLAND,8241412527,NaN,NaN,Wielka Brytania,strati-matyja,1 LO ram
2,3,Papież,Kristian,Alan,4151,2007-12-10 00:00:00,Reykjanesbaer - Islandia,NaN,Paszport,ER0669334,Islandia,kristiano2007@gmail.com,1 LO ram
3,4,Kukieła,Amelia,Magdalena,4152,2007-10-30 00:00:00,Bielsko-Biała,7303002809,NaN,NaN,Polska,magda@wp.eu,1 LO ram
4,5,Patacz,Amelia,Michalina,1853,2007-04-16 00:00:00,POLANICA ZDRÓJ,7241601308,Inny dokument ze zdjęciem,CCF287398,Szwecja,edzia1703@o2.pl,1 LO ram
...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,99.0,Włodraczyk,Wiktoria,NaN,4060,2008-04-27 00:00:00,Wałcz,8242702500,NaN,NaN,Turcja,NaN,8 sp uzup
99,100.0,Yalovskyi,Yaroslav,NaN,4061,2008-11-21 00:00:00,Kijów,8312114459,NaN,NaN,Ukraina,juliajalov@gmail.com;fogartu@qulook.com,8 sp uzup
100,101.0,Krawczak,Matthew,Peter,4062,2008-03-04 00:00:00,ST.Thomas,8230413375,NaN,NaN,Kanada,leskrawczak@Gmail.com,8 sp uzup
101,102.0,Lenkiewicz,Zuzanna,NaN,4063,2008-05-09 00:00:00,Londyn,8250912500,NaN,NaN,Wielka Brytania,anka_jak@yahoo.com,8 sp uzup
102,103.0,Radzimiński,Igor,NaN,4624,2009-04-12 00:00:00,Warszawa,9241206590,NaN,NaN,Moskwa,a.radziminska@wp.pl,8 sp uzup

In [58]:
db.dropna(subset=['L.p.'], inplace = True)

In [59]:
db.drop_duplicates(subset=['Nazwisko ucznia', 'Imię ucznia', 'Klasa'], inplace = True)

In [60]:
db

,L.p.,Nazwisko ucznia,Imię ucznia,Drugie imię ucznia,nr ksiegi,Data urodzenia ucznia,Miejsce urodzen..,PESEL ucznia,Inny dokument t..,Nr i seria doku..,Kraj pobytu ucznia,Email,Klasa
0,1,Staśkiewicz,Anna,Magdalena,4149,2007-12-07 00:00:00,Piła,7320704782,NaN,NaN,Niemcy,alinastaskiewicz@o2.pl,1 LO ram
1,2,Chicińska-Ryster,Nikola,Żaneta,4150,2008-04-14 00:00:00,CHESTERFIELD ENGLAND,8241412527,NaN,NaN,Wielka Brytania,strati-matyja,1 LO ram
2,3,Papież,Kristian,Alan,4151,2007-12-10 00:00:00,Reykjanesbaer - Islandia,NaN,Paszport,ER0669334,Islandia,kristiano2007@gmail.com,1 LO ram
3,4,Kukieła,Amelia,Magdalena,4152,2007-10-30 00:00:00,Bielsko-Biała,7303002809,NaN,NaN,Polska,magda@wp.eu,1 LO ram
4,5,Patacz,Amelia,Michalina,1853,2007-04-16 00:00:00,POLANICA ZDRÓJ,7241601308,Inny dokument ze zdjęciem,CCF287398,Szwecja,edzia1703@o2.pl,1 LO ram
...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,99.0,Włodraczyk,Wiktoria,NaN,4060,2008-04-27 00:00:00,Wałcz,8242702500,NaN,NaN,Turcja,NaN,8 sp uzup
99,100.0,Yalovskyi,Yaroslav,NaN,4061,2008-11-21 00:00:00,Kijów,8312114459,NaN,NaN,Ukraina,juliajalov@gmail.com;fogartu@qulook.com,8 sp uzup
100,101.0,Krawczak,Matthew,Peter,4062,2008-03-04 00:00:00,ST.Thomas,8230413375,NaN,NaN,Kanada,leskrawczak@Gmail.com,8 sp uzup
101,102.0,Lenkiewicz,Zuzanna,NaN,4063,2008-05-09 00:00:00,Londyn,8250912500,NaN,NaN,Wielka Brytania,anka_jak@yahoo.com,8 sp uzup
102,103.0,Radzimiński,Igor,NaN,4624,2009-04-12 00:00:00,Warszawa,9241206590,NaN,NaN,Moskwa,a.radziminska@wp.pl,8 sp uzup

In [61]:
db['Data urodzenia ucznia'] = pd.to_datetime(db['Data urodzenia ucznia'], errors='coerce')

C:\Users\Wojciech\AppData\Local\Temp\ipykernel_2524\1309943092.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  db['Data urodzenia ucznia'] = pd.to_datetime(db['Data urodzenia ucznia'], errors='coerce')

In [62]:
db

,L.p.,Nazwisko ucznia,Imię ucznia,Drugie imię ucznia,nr ksiegi,Data urodzenia ucznia,Miejsce urodzen..,PESEL ucznia,Inny dokument t..,Nr i seria doku..,Kraj pobytu ucznia,Email,Klasa
0,1,Staśkiewicz,Anna,Magdalena,4149,2007-12-07,Piła,7320704782,NaN,NaN,Niemcy,alinastaskiewicz@o2.pl,1 LO ram
1,2,Chicińska-Ryster,Nikola,Żaneta,4150,2008-04-14,CHESTERFIELD ENGLAND,8241412527,NaN,NaN,Wielka Brytania,strati-matyja,1 LO ram
2,3,Papież,Kristian,Alan,4151,2007-12-10,Reykjanesbaer - Islandia,NaN,Paszport,ER0669334,Islandia,kristiano2007@gmail.com,1 LO ram
3,4,Kukieła,Amelia,Magdalena,4152,2007-10-30,Bielsko-Biała,7303002809,NaN,NaN,Polska,magda@wp.eu,1 LO ram
4,5,Patacz,Amelia,Michalina,1853,2007-04-16,POLANICA ZDRÓJ,7241601308,Inny dokument ze zdjęciem,CCF287398,Szwecja,edzia1703@o2.pl,1 LO ram
...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,99.0,Włodraczyk,Wiktoria,NaN,4060,2008-04-27,Wałcz,8242702500,NaN,NaN,Turcja,NaN,8 sp uzup
99,100.0,Yalovskyi,Yaroslav,NaN,4061,2008-11-21,Kijów,8312114459,NaN,NaN,Ukraina,juliajalov@gmail.com;fogartu@qulook.com,8 sp uzup
100,101.0,Krawczak,Matthew,Peter,4062,2008-03-04,ST.Thomas,8230413375,NaN,NaN,Kanada,leskrawczak@Gmail.com,8 sp uzup
101,102.0,Lenkiewicz,Zuzanna,NaN,4063,2008-05-09,Londyn,8250912500,NaN,NaN,Wielka Brytania,anka_jak@yahoo.com,8 sp uzup
102,103.0,Radzimiński,Igor,NaN,4624,2009-04-12,Warszawa,9241206590,NaN,NaN,Moskwa,a.radziminska@wp.pl,8 sp uzup

In [63]:
df.columns

Index(['L.p.', 'Nazwisko', 'Imię', 'e-mail', 'Klasa'], dtype='object')

In [64]:
df.columns = ['L.p.', 'Nazwisko', 'Imię', 'e-mail', 'Klasa']

In [92]:
db.columns

Index(['L.p.', 'Nazwisko ucznia', 'Imię ucznia', 'Drugie imię ucznia',
       'nr ksiegi', 'Data urodzenia ucznia', 'Miejsce urodzen..',
       'PESEL ucznia', 'Inny dokument t..', 'Nr i seria doku..',
       'Kraj pobytu ucznia', 'Email', 'Klasa'],
      dtype='object')

In [103]:
db.columns = ['L.p.', 'Nazwisko', 'Imię', 'Drugie imię', 'nr_ksiegi',
       'Data urodzenia', 'Miejsce ur', 'PESEL', 'Inny dok', 'Nr i seria',
       'Kraj', 'e-mail', 'Klasa']

In [67]:
df

,L.p.,Nazwisko,Imię,e-mail,Klasa
1,1.0,Bembnista,Dawid,jolbem1978@gmail.com tombem30@wp.pl,1 LO ram
2,2.0,Bryliński,Bogdan,contact@olgabrylinska.com,1 LO ram
3,3.0,Chicińska-Ryster,Nikola,izabela2169@wp.pl,1 LO ram
4,4.0,Ciźla,Nadia,cpn.fit@gmail.com,1 LO ram
5,5.0,Czarnocka,Nikoletta,tamara.c@wp.pl,1 LO ram
...,...,...,...,...,...
91,91.0,Łapicz-Biedź,Zachary Oliver,wbiedz@gmail.com,8 SP uzup
92,92.0,Łoboz,Julia Danuta,gwiazdap@op.pl,8 SP uzup
93,93.0,Śladewski,Antoni,jacek.sladewski@msz.gov.pl,8 SP uzup
94,94.0,Żukrowska,Anastazja Apolonia,k.a.zukrowska@gmail.com,8 SP uzup
95,95.0,Lenkiewicz,Zuzanna,anka_jak@yahoo.com,8 SP uzup

In [68]:
# d = df.merge(db[['Nazwisko', 'Imię', 'Drugie imię','nr_ksiegi', 'Data urodzenia', 'Miejsce ur','PESEL', 'Klasa']], on=['Nazwisko', 'Imię', 'Klasa'], how = 'left')

In [104]:
cc = pd.read_excel('../import_uczniow.xls')

In [105]:
cc.columns

Index(['Nr z dziennika', 'Imiona', 'Nazwisko', 'Płęć', 'Nr Karty',
       'Nr księgi ucznia', 'Pesel', 'Tel Ucznia', 'e-mail ucznia',
       'Data urodzenia', 'Miejsce urodzenia', 'Miejsce urodzenia miejscownik',
       'Ulica i nr domu', 'Kod pocztowy i miejscowość ', 'Województwo',
       'imię i nazwisko matki', 'numer telefonu do matki',
       'imię i nazwisko ojca', 'numer telefonu do ojca', 'email opiekun1 ',
       'email opiekun 2', 'uwagi ucznia'],
      dtype='object')

In [131]:
dd = db.loc[db['Klasa'] =='3 sp ram']

In [132]:
dd.head()

,L.p.,Nazwisko,Imię,Drugie imię,nr_ksiegi,Data urodzenia,Miejsce ur,PESEL,Inny dok,Nr i seria,Kraj,e-mail,Klasa
0,1.0,Bryliński,Aleksander,Piotr,3507.0,2013-01-06,Kraków,13210603415.0,NaN,NaN,Madagaskar,contact@olgabrylinska.com,3 sp ram
1,2.0,Matuszczak,Gabriel,Stefan,3508.0,2013-07-15,Kościerzyna,13271500915.0,NaN,NaN,Polska,izabelamaria@gmail.com,3 sp ram
2,3.0,Magdziarz,Jan,NaN,3509.0,2013-02-11,Lublin,NaN,Inny dokument ze zdjęciem,DEE115004,Włochy,i.magdziarz@wp.pl,3 sp ram
3,4.0,Kucharska,Julia,NaN,3510.0,2013-09-27,Ełk,13292705540.0,NaN,NaN,Stany Zjednoczone,magdalapszys@wp.pl,3 sp ram
4,5.0,Barrau-Kamińska,Ewa,Hermine,3511.0,2013-10-08,Warszawa,13300806148.0,NaN,NaN,Francja,aniaannakaminska@outlook.com,3 sp ram

In [133]:
# Inicjalizujemy pustą ramkę danych z odpowiednimi kolumnami
cd = pd.DataFrame(columns=cc.columns)

# Przypisujemy kolumny z dd do odpowiednich kolumn w cd
cd[['Nr księgi ucznia', 'Imiona', 'Nazwisko', 'Data urodzenia', 'Miejsce urodzenia', 'Pesel', 'e-mail ucznia']] = dd[['nr_ksiegi', 'Imię', 'Nazwisko', 'Data urodzenia', 'Miejsce ur', 'PESEL', 'e-mail']]

# Zostawiamy pozostałe kolumny puste, ponieważ nie mamy dla nich danych w dd

In [134]:
cd.head()

,Nr z dziennika,Imiona,Nazwisko,Płęć,Nr Karty,Nr księgi ucznia,Pesel,Tel Ucznia,e-mail ucznia,Data urodzenia,...,Ulica i nr domu,Kod pocztowy i miejscowość,Województwo,imię i nazwisko matki,numer telefonu do matki,imię i nazwisko ojca,numer telefonu do ojca,email opiekun1,email opiekun 2,uwagi ucznia
0,NaN,Aleksander,Bryliński,NaN,NaN,3507.0,13210603415.0,NaN,contact@olgabrylinska.com,2013-01-06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Gabriel,Matuszczak,NaN,NaN,3508.0,13271500915.0,NaN,izabelamaria@gmail.com,2013-07-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Jan,Magdziarz,NaN,NaN,3509.0,NaN,NaN,i.magdziarz@wp.pl,2013-02-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Julia,Kucharska,NaN,NaN,3510.0,13292705540.0,NaN,magdalapszys@wp.pl,2013-09-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Ewa,Barrau-Kamińska,NaN,NaN,3511.0,13300806148.0,NaN,aniaannakaminska@outlook.com,2013-10-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
# Usuwamy '.0' na końcu wartości, konwertujemy na string
cd['Pesel'] = cd['Pesel'].astype(str).str.split('.').str[0]

# Uzupełniamy zera na początku do 11 cyfr
cd['Pesel'] = cd['Pesel'].str.zfill(11)

# Usuwamy '.0' na końcu wartości, konwertujemy na string
cd['Nr księgi ucznia'] = cd['Nr księgi ucznia'].astype(str).str.split('.').str[0]

In [136]:
cd

,Nr z dziennika,Imiona,Nazwisko,Płęć,Nr Karty,Nr księgi ucznia,Pesel,Tel Ucznia,e-mail ucznia,Data urodzenia,...,Ulica i nr domu,Kod pocztowy i miejscowość,Województwo,imię i nazwisko matki,numer telefonu do matki,imię i nazwisko ojca,numer telefonu do ojca,email opiekun1,email opiekun 2,uwagi ucznia
0,NaN,Aleksander,Bryliński,NaN,NaN,3507,13210603415,NaN,contact@olgabrylinska.com,2013-01-06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Gabriel,Matuszczak,NaN,NaN,3508,13271500915,NaN,izabelamaria@gmail.com,2013-07-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Jan,Magdziarz,NaN,NaN,3509,00000000nan,NaN,i.magdziarz@wp.pl,2013-02-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Julia,Kucharska,NaN,NaN,3510,13292705540,NaN,magdalapszys@wp.pl,2013-09-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Ewa,Barrau-Kamińska,NaN,NaN,3511,13300806148,NaN,aniaannakaminska@outlook.com,2013-10-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Cyprian,Błażejczyk,NaN,NaN,3512,13212609098,NaN,blazejczykmalgorzata1@gmail.com,2013-01-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Franciszek,Ciarciński,NaN,NaN,3513,13210501171,NaN,szmery80@gmail.com,2013-01-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Kuba,Dawidowski,NaN,NaN,3514,13281707276,NaN,bd@sailoceans.com,2013-08-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Daniel,Farrell,NaN,NaN,3515,13233008592,NaN,anna.farrell2011@gmail.com,2013-03-30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Marcel,Głogowski,NaN,NaN,3516,13290609556,NaN,kasia.zub@wp.pl,2013-09-06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Adam,Harbi,NaN,NaN,3517,14233110614,NaN,Izabela_fharbi@wp.pl,2014-03-31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Daniella,Heugh,NaN,NaN,3518,00000000nan,NaN,ewa.heugh@gmail.com,2014-06-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Julia,Juszczyk,NaN,NaN,3519,00000000nan,NaN,kassjuszczyk@gmail.com,2013-10-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Leonard,Kalota,NaN,NaN,3520,13290211638,NaN,judyta.kalota@gmail.com,2013-09-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Krystian,Masalski,NaN,NaN,3521,13290808498,NaN,masalski1@wp.pl,2013-09-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Nadia,Misztal Alvarez,NaN,NaN,3522,13312011088,NaN,jmisztal01@gmail.com,2013-11-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Joanna,Nowakowska,NaN,NaN,3523,13271905963,NaN,nowakowska.k@op.pl,2013-07-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Nadia,Pac,NaN,NaN,3524,12311911382,NaN,sholka999@wp.pl,2012-11-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,Filip,Piasecki,NaN,NaN,3525,13322710339,NaN,losmagda@wp.pl,2013-12-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Victor,Planas Majchrzak,NaN,NaN,3526,14240200070,NaN,klaudiab201@gmail.com,2014-04-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,Bartek,Polewski,NaN,NaN,3527,14240408256,NaN,justyna.jarzembinska@wp.pl,2014-04-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,Stanisław,Rybicki,NaN,NaN,3528,13291007438,NaN,flightcrew17@gmail.com,2013-09-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,Georgy,Safonov,NaN,NaN,3529,13302509810,NaN,jmetelitsa@gmail.com,2013-10-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,Tulasi,Salwach,NaN,NaN,3530,13280307781,NaN,salwachola@gmail.com,2013-08-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,Fode,Sylla,NaN,NaN,3531,13260711937,NaN,sylla.jack5@gmail.com,2013-06-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,Nel,Szałapska,NaN,NaN,3532,13300310263,NaN,kwiatilo@wp.pl,2013-10-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,Natalia,Tybuś,NaN,NaN,3533,13232904287,NaN,etybus@gmail.com,2013-03-29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Adam,Zaky,NaN,NaN,3534,13212111273,NaN,bbecia@yahoo.co.uk,2013-01-21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,Laila,Abouzeid,NaN,NaN,3535,01328081330,NaN,NaN,2013-08-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,Kisel,Apolonia,NaN,NaN,3536,01328100928,NaN,NaN,2013-08-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,Apolonia,Kisiel,NaN,NaN,3537,01328100928,NaN,NaN,2014-08-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Julia,Kucharska,NaN,NaN,3538,01329270554,NaN,NaN,2013-09-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,Sylwia,Kula,NaN,NaN,3539,01321231034,NaN,NaN,2013-01-23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,Aleksandra,Mudlaff,NaN,NaN,3540,01330160090,NaN,NaN,2013-10-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,Cody,Murzanski,NaN,NaN,3541,01324010787,NaN,NaN,2013-04-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [137]:
cd['Płęć'] = cd['Imiona'].apply(lambda x: 'k' if str(x).strip().endswith('a') else 'm')

In [138]:
cd

,Nr z dziennika,Imiona,Nazwisko,Płęć,Nr Karty,Nr księgi ucznia,Pesel,Tel Ucznia,e-mail ucznia,Data urodzenia,...,Ulica i nr domu,Kod pocztowy i miejscowość,Województwo,imię i nazwisko matki,numer telefonu do matki,imię i nazwisko ojca,numer telefonu do ojca,email opiekun1,email opiekun 2,uwagi ucznia
0,NaN,Aleksander,Bryliński,m,NaN,3507,13210603415,NaN,contact@olgabrylinska.com,2013-01-06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Gabriel,Matuszczak,m,NaN,3508,13271500915,NaN,izabelamaria@gmail.com,2013-07-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Jan,Magdziarz,m,NaN,3509,00000000nan,NaN,i.magdziarz@wp.pl,2013-02-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Julia,Kucharska,k,NaN,3510,13292705540,NaN,magdalapszys@wp.pl,2013-09-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Ewa,Barrau-Kamińska,k,NaN,3511,13300806148,NaN,aniaannakaminska@outlook.com,2013-10-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Cyprian,Błażejczyk,m,NaN,3512,13212609098,NaN,blazejczykmalgorzata1@gmail.com,2013-01-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Franciszek,Ciarciński,m,NaN,3513,13210501171,NaN,szmery80@gmail.com,2013-01-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Kuba,Dawidowski,k,NaN,3514,13281707276,NaN,bd@sailoceans.com,2013-08-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,Daniel,Farrell,m,NaN,3515,13233008592,NaN,anna.farrell2011@gmail.com,2013-03-30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Marcel,Głogowski,m,NaN,3516,13290609556,NaN,kasia.zub@wp.pl,2013-09-06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Adam,Harbi,m,NaN,3517,14233110614,NaN,Izabela_fharbi@wp.pl,2014-03-31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Daniella,Heugh,k,NaN,3518,00000000nan,NaN,ewa.heugh@gmail.com,2014-06-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,Julia,Juszczyk,k,NaN,3519,00000000nan,NaN,kassjuszczyk@gmail.com,2013-10-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,Leonard,Kalota,m,NaN,3520,13290211638,NaN,judyta.kalota@gmail.com,2013-09-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Krystian,Masalski,m,NaN,3521,13290808498,NaN,masalski1@wp.pl,2013-09-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Nadia,Misztal Alvarez,k,NaN,3522,13312011088,NaN,jmisztal01@gmail.com,2013-11-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Joanna,Nowakowska,k,NaN,3523,13271905963,NaN,nowakowska.k@op.pl,2013-07-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Nadia,Pac,k,NaN,3524,12311911382,NaN,sholka999@wp.pl,2012-11-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,Filip,Piasecki,m,NaN,3525,13322710339,NaN,losmagda@wp.pl,2013-12-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Victor,Planas Majchrzak,m,NaN,3526,14240200070,NaN,klaudiab201@gmail.com,2014-04-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,Bartek,Polewski,m,NaN,3527,14240408256,NaN,justyna.jarzembinska@wp.pl,2014-04-04,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,Stanisław,Rybicki,m,NaN,3528,13291007438,NaN,flightcrew17@gmail.com,2013-09-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,Georgy,Safonov,m,NaN,3529,13302509810,NaN,jmetelitsa@gmail.com,2013-10-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,Tulasi,Salwach,m,NaN,3530,13280307781,NaN,salwachola@gmail.com,2013-08-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,Fode,Sylla,m,NaN,3531,13260711937,NaN,sylla.jack5@gmail.com,2013-06-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,Nel,Szałapska,m,NaN,3532,13300310263,NaN,kwiatilo@wp.pl,2013-10-03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,Natalia,Tybuś,k,NaN,3533,13232904287,NaN,etybus@gmail.com,2013-03-29,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,Adam,Zaky,m,NaN,3534,13212111273,NaN,bbecia@yahoo.co.uk,2013-01-21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,Laila,Abouzeid,k,NaN,3535,01328081330,NaN,NaN,2013-08-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,Kisel,Apolonia,m,NaN,3536,01328100928,NaN,NaN,2013-08-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,Apolonia,Kisiel,k,NaN,3537,01328100928,NaN,NaN,2014-08-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,Julia,Kucharska,k,NaN,3538,01329270554,NaN,NaN,2013-09-27,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,Sylwia,Kula,k,NaN,3539,01321231034,NaN,NaN,2013-01-23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,Aleksandra,Mudlaff,k,NaN,3540,01330160090,NaN,NaN,2013-10-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,Cody,Murzanski,m,NaN,3541,01324010787,NaN,NaN,2013-04-01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [139]:
cd.fillna('', inplace = True)

In [140]:
cd

,Nr z dziennika,Imiona,Nazwisko,Płęć,Nr Karty,Nr księgi ucznia,Pesel,Tel Ucznia,e-mail ucznia,Data urodzenia,...,Ulica i nr domu,Kod pocztowy i miejscowość,Województwo,imię i nazwisko matki,numer telefonu do matki,imię i nazwisko ojca,numer telefonu do ojca,email opiekun1,email opiekun 2,uwagi ucznia
0,,Aleksander,Bryliński,m,,3507,13210603415,,contact@olgabrylinska.com,2013-01-06,...,,,,,,,,,,
1,,Gabriel,Matuszczak,m,,3508,13271500915,,izabelamaria@gmail.com,2013-07-15,...,,,,,,,,,,
2,,Jan,Magdziarz,m,,3509,00000000nan,,i.magdziarz@wp.pl,2013-02-11,...,,,,,,,,,,
3,,Julia,Kucharska,k,,3510,13292705540,,magdalapszys@wp.pl,2013-09-27,...,,,,,,,,,,
4,,Ewa,Barrau-Kamińska,k,,3511,13300806148,,aniaannakaminska@outlook.com,2013-10-08,...,,,,,,,,,,
5,,Cyprian,Błażejczyk,m,,3512,13212609098,,blazejczykmalgorzata1@gmail.com,2013-01-26,...,,,,,,,,,,
6,,Franciszek,Ciarciński,m,,3513,13210501171,,szmery80@gmail.com,2013-01-05,...,,,,,,,,,,
7,,Kuba,Dawidowski,k,,3514,13281707276,,bd@sailoceans.com,2013-08-17,...,,,,,,,,,,
8,,Daniel,Farrell,m,,3515,13233008592,,anna.farrell2011@gmail.com,2013-03-30,...,,,,,,,,,,
9,,Marcel,Głogowski,m,,3516,13290609556,,kasia.zub@wp.pl,2013-09-06,...,,,,,,,,,,
10,,Adam,Harbi,m,,3517,14233110614,,Izabela_fharbi@wp.pl,2014-03-31,...,,,,,,,,,,
11,,Daniella,Heugh,k,,3518,00000000nan,,ewa.heugh@gmail.com,2014-06-20,...,,,,,,,,,,
12,,Julia,Juszczyk,k,,3519,00000000nan,,kassjuszczyk@gmail.com,2013-10-10,...,,,,,,,,,,
13,,Leonard,Kalota,m,,3520,13290211638,,judyta.kalota@gmail.com,2013-09-02,...,,,,,,,,,,
14,,Krystian,Masalski,m,,3521,13290808498,,masalski1@wp.pl,2013-09-08,...,,,,,,,,,,
15,,Nadia,Misztal Alvarez,k,,3522,13312011088,,jmisztal01@gmail.com,2013-11-20,...,,,,,,,,,,
16,,Joanna,Nowakowska,k,,3523,13271905963,,nowakowska.k@op.pl,2013-07-19,...,,,,,,,,,,
17,,Nadia,Pac,k,,3524,12311911382,,sholka999@wp.pl,2012-11-19,...,,,,,,,,,,
18,,Filip,Piasecki,m,,3525,13322710339,,losmagda@wp.pl,2013-12-27,...,,,,,,,,,,
19,,Victor,Planas Majchrzak,m,,3526,14240200070,,klaudiab201@gmail.com,2014-04-02,...,,,,,,,,,,
20,,Bartek,Polewski,m,,3527,14240408256,,justyna.jarzembinska@wp.pl,2014-04-04,...,,,,,,,,,,
21,,Stanisław,Rybicki,m,,3528,13291007438,,flightcrew17@gmail.com,2013-09-10,...,,,,,,,,,,
22,,Georgy,Safonov,m,,3529,13302509810,,jmetelitsa@gmail.com,2013-10-25,...,,,,,,,,,,
23,,Tulasi,Salwach,m,,3530,13280307781,,salwachola@gmail.com,2013-08-03,...,,,,,,,,,,
24,,Fode,Sylla,m,,3531,13260711937,,sylla.jack5@gmail.com,2013-06-07,...,,,,,,,,,,
25,,Nel,Szałapska,m,,3532,13300310263,,kwiatilo@wp.pl,2013-10-03,...,,,,,,,,,,
26,,Natalia,Tybuś,k,,3533,13232904287,,etybus@gmail.com,2013-03-29,...,,,,,,,,,,
27,,Adam,Zaky,m,,3534,13212111273,,bbecia@yahoo.co.uk,2013-01-21,...,,,,,,,,,,
28,,Laila,Abouzeid,k,,3535,01328081330,,,2013-08-08,...,,,,,,,,,,
29,,Kisel,Apolonia,m,,3536,01328100928,,,2013-08-10,...,,,,,,,,,,
30,,Apolonia,Kisiel,k,,3537,01328100928,,,2014-08-10,...,,,,,,,,,,
31,,Julia,Kucharska,k,,3538,01329270554,,,2013-09-27,...,,,,,,,,,,
32,,Sylwia,Kula,k,,3539,01321231034,,,2013-01-23,...,,,,,,,,,,
33,,Aleksandra,Mudlaff,k,,3540,01330160090,,,2013-10-16,...,,,,,,,,,,
34,,Cody,Murzanski,m,,3541,01324010787,,,2013-04-01,...,,,,,,,,,,

In [141]:
cd['Imiona'] = cd['Imiona'].str.title()
cd['Nazwisko'] = cd['Nazwisko'].str.title()

In [142]:
cd.to_csv('klasa3SPram.csv', sep = ';', encoding = 'windows-1250', errors='ignore', index=False)

In [282]:
db.columns

Index(['L.p.', 'Nazwisko', 'Imię', 'Drugie imię', 'nr_ksiegi',
       'Data urodzenia', 'Miejsce ur', 'PESEL', 'Inny dok', 'Nr i seria',
       'Kraj', 'e-mail', 'Klasa'],
      dtype='object')

In [289]:
db.Klasa.unique()

array(['1 LO ram', '1 LO uzup', '1 sp ram', '1 sp uzup', '2 LO ram',
       '2 LO uzup', '2 sp ram', '2 sp uzup', '3 LO ram', '3 LO uzup',
       '3 sp ram', '3 sp uzup', '4 LO ram', '4 LO uzup', '4 sp ram',
       '4 sp uzup', '5 sp ram', '5 sp uzup', '6 sp ram', '6 sp uzup',
       '7 sp ram', '7 sp uzup', '8 sp ram', '8 sp uzup'], dtype=object)

In [81]:
db.loc[db['Klasa'] == '3 sp ram']

,L.p.,Nazwisko ucznia,Imię ucznia,Drugie imię ucznia,nr ksiegi,Data urodzenia ucznia,Miejsce urodzen..,PESEL ucznia,Inny dokument t..,Nr i seria doku..,Kraj pobytu ucznia,Email,Klasa
0,1.0,Bryliński,Aleksander,Piotr,3507.0,2013-01-06,Kraków,13210603415.0,NaN,NaN,Madagaskar,contact@olgabrylinska.com,3 sp ram
1,2.0,Matuszczak,Gabriel,Stefan,3508.0,2013-07-15,Kościerzyna,13271500915.0,NaN,NaN,Polska,izabelamaria@gmail.com,3 sp ram
2,3.0,Magdziarz,Jan,NaN,3509.0,2013-02-11,Lublin,NaN,Inny dokument ze zdjęciem,DEE115004,Włochy,i.magdziarz@wp.pl,3 sp ram
3,4.0,Kucharska,Julia,NaN,3510.0,2013-09-27,Ełk,13292705540.0,NaN,NaN,Stany Zjednoczone,magdalapszys@wp.pl,3 sp ram
4,5.0,Barrau-Kamińska,Ewa,Hermine,3511.0,2013-10-08,Warszawa,13300806148.0,NaN,NaN,Francja,aniaannakaminska@outlook.com,3 sp ram
5,6.0,Błażejczyk,Cyprian,Oskar,3512.0,2013-01-26,Craigavon,13212609098.0,NaN,NaN,Wielka Brytania,blazejczykmalgorzata1@gmail.com,3 sp ram
6,7.0,Ciarciński,Franciszek,NaN,3513.0,2013-01-05,Świebodzice,13210501171.0,NaN,NaN,Ukraina,szmery80@gmail.com,3 sp ram
7,8.0,Dawidowski,Kuba,NaN,3514.0,2013-08-17,Warszawa,13281707276.0,NaN,NaN,Stany Zjednoczone,bd@sailoceans.com,3 sp ram
8,9.0,Farrell,Daniel,NaN,3515.0,2013-03-30,Auckland,13233008592.0,NaN,NaN,Holandia,anna.farrell2011@gmail.com,3 sp ram
9,10.0,Głogowski,Marcel,NaN,3516.0,2013-09-06,Ustka,13290609556.0,NaN,NaN,Niemcy,kasia.zub@wp.pl,3 sp ram
10,11.0,Harbi,Adam,NaN,3517.0,2014-03-31,Egipt,14233110614.0,NaN,NaN,Egipt,Izabela_fharbi@wp.pl,3 sp ram
11,12.0,Heugh,Daniella,NaN,3518.0,2014-06-20,Wrocław,NaN,paszport,EK 9555242,RPA,ewa.heugh@gmail.com,3 sp ram
12,13.0,Juszczyk,Julia,Agata,3519.0,2013-10-10,Chełm,NaN,NaN,NaN,Francja,kassjuszczyk@gmail.com,3 sp ram
13,14.0,Kalota,Leonard,NaN,3520.0,2013-09-02,Yogyakarta,13290211638.0,NaN,NaN,Indonezja,judyta.kalota@gmail.com,3 sp ram
14,15.0,Masalski,Krystian,NaN,3521.0,2013-09-08,Halifax,13290808498.0,NaN,NaN,Wielka Brytania,masalski1@wp.pl,3 sp ram
15,16.0,Misztal Alvarez,Nadia,NaN,3522.0,2013-11-20,Ponteareas,13312011088.0,NaN,NaN,Hiszpania,jmisztal01@gmail.com,3 sp ram
16,17.0,Nowakowska,Joanna,NaN,3523.0,2013-07-19,Tychy,13271905963.0,NaN,NaN,Kazachstan,nowakowska.k@op.pl,3 sp ram
17,18.0,Pac,Nadia,NaN,3524.0,2012-11-19,Gdańsk,12311911382.0,NaN,NaN,Grecja,sholka999@wp.pl,3 sp ram
18,19.0,Piasecki,Filip,Einar,3525.0,2013-12-27,Bergen,13322710339.0,NaN,NaN,Norwegia,losmagda@wp.pl,3 sp ram
19,20.0,Planas Majchrzak,Victor,NaN,3526.0,2014-04-02,Kraków,14240200070.0,NaN,NaN,Hiszpania,klaudiab201@gmail.com,3 sp ram
20,21.0,Polewski,Bartek,Dawid,3527.0,2014-04-04,Bielsko-Biała,14240408256.0,NaN,NaN,Grecja,justyna.jarzembinska@wp.pl,3 sp ram
21,22.0,Rybicki,Stanisław,NaN,3528.0,2013-09-10,Gdańsk,13291007438.0,NaN,NaN,Grenada,flightcrew17@gmail.com,3 sp ram
22,23.0,Safonov,Georgy,NaN,3529.0,2013-10-25,Kraków,13302509810.0,NaN,NaN,Szwecja,jmetelitsa@gmail.com,3 sp ram
23,24.0,Salwach,Tulasi,Mandżari,3530.0,2013-08-03,Koszalin,13280307781.0,NaN,NaN,Wielka Brytania,salwachola@gmail.com,3 sp ram
24,25.0,Sylla,Fode,Zygmund,3531.0,2013-06-07,Exeter/ Anglia,13260711937.0,NaN,NaN,Wielka Brytania,sylla.jack5@gmail.com,3 sp ram
25,26.0,Szałapska,Nel,NaN,3532.0,2013-10-03,Opoczno,13300310263.0,NaN,NaN,Niemcy,kwiatilo@wp.pl,3 sp ram
26,27.0,Tybuś,Natalia,Gizela,3533.0,2013-03-29,Gdynia,13232904287.0,NaN,NaN,Irlandia,etybus@gmail.com,3 sp ram
27,28.0,Zaky,Adam,NaN,3534.0,2013-01-21,Londyn,13212111273.0,NaN,NaN,Wielka Brytania,bbecia@yahoo.co.uk,3 sp ram
28,29.0,Abouzeid,Laila,NaN,3535.0,2013-08-08,Egipt/Kair,1328081330.0,NaN,NaN,Egipt,NaN,3 sp ram
29,30.0,Apolonia,Kisel,Maria,3536.0,2013-08-10,Edinburgh,1328100928.0,NaN,NaN,Wielka Brytania,NaN,3 sp ram
30,31.0,Kisiel,Apolonia,Maria,3537.0,2014-08-10,Edinburgh,1328100928.0,NaN,NaN,Wielka Brytania,NaN,3 sp ram
31,32.0,Kucharska,Julia,Brak,3538.0,2013-09-27,Ełk,1329270554.0,NaN,NaN,Stany Zjednoczone,NaN,3 sp ram
32,33.0,Kula,Sylwia,NaN,3539.0,2013-01-23,Mysłowice,1321231034.0,NaN,NaN,Czechy,NaN,3 sp ram
33,34.0,Mudlaff,Aleksandra,NaN,3540.0,2013-10-16,Gdańsk,1330160090.0,NaN,NaN,Cypr,NaN,3 sp ram
34,35.0,Murzanski,Cody,Jacob,3541.0,2013-04-01,"Hoffman Estates Il, U.S.A.",1324010787.0,NaN,NaN,Stany Zjednoczone,NaN,3 sp ram