In [159]:
import pandas as pd
import numpy as np
import openpyxl

In [160]:
zakladki = pd.read_excel('Lista uczniów SP_LO_2022_2023 propozycje ocen rocznych.xlsx', sheet_name=None).keys()
zakladki

dict_keys(['1 SP uzup', '1 SP ram', '2 SP uzup', '2 SP ram', '3 SP uzup', '3 SP ram', '4 SP ram', '4 SP uzup', '5 SP uzup', '5 SP ram', '6 SP ram', '6 SP uzup', '7 SP uzup', '8 SP uzup', '7 SP ram', '8 SP ram', '1 LO uzup', '1 LO ram', '2 LO ram', '2 LO uzup', '3 LO uzup', '3 LO ram', '4 LO uzup', 'Arkusz1'])

In [161]:
zakladki = ['1 SP uzup', '1 SP ram', '2 SP uzup', '2 SP ram', '3 SP uzup', '3 SP ram', '4 SP ram', '4 SP uzup', '5 SP uzup', '5 SP ram', '6 SP ram', '6 SP uzup', '7 SP uzup', '8 SP uzup', '7 SP ram', '8 SP ram', '1 LO uzup', '1 LO ram', '2 LO ram', '2 LO uzup', '3 LO uzup', '3 LO ram', '4 LO uzup']
zakladki.sort()
# zakladki

In [162]:
df = pd.concat(pd.read_excel('Lista uczniów SP_LO_2022_2023 propozycje ocen rocznych.xlsx', sheet_name=s, usecols='B:E', skiprows=1).assign(Klasa = s) for s in zakladki)

In [163]:
df.columns

Index(['L.p.', 'Nazwisko ucznia', 'Imię/Imiona', 'e-mail', 'Klasa'], dtype='object')

In [164]:
df.dropna(subset=['L.p.', 'Nazwisko ucznia'], inplace = True)

In [165]:
df.drop_duplicates(subset=['Nazwisko ucznia', 'Imię/Imiona','Klasa'])
df

,L.p.,Nazwisko ucznia,Imię/Imiona,e-mail,Klasa
1,1.0,Bembnista,Dawid,jolbem1978@gmail.com tombem30@wp.pl,1 LO ram
2,2.0,Bryliński,Bogdan,contact@olgabrylinska.com,1 LO ram
3,3.0,Chicińska-Ryster,Nikola,izabela2169@wp.pl,1 LO ram
4,4.0,Ciźla,Nadia,cpn.fit@gmail.com,1 LO ram
5,5.0,Czarnocka,Nikoletta,tamara.c@wp.pl,1 LO ram
...,...,...,...,...,...
91,91.0,Łapicz-Biedź,Zachary Oliver,wbiedz@gmail.com,8 SP uzup
92,92.0,Łoboz,Julia Danuta,gwiazdap@op.pl,8 SP uzup
93,93.0,Śladewski,Antoni,jacek.sladewski@msz.gov.pl,8 SP uzup
94,94.0,Żukrowska,Anastazja Apolonia,k.a.zukrowska@gmail.com,8 SP uzup
95,95.0,Lenkiewicz,Zuzanna,anka_jak@yahoo.com,8 SP uzup

In [134]:
x = df.loc[df['Klasa']=='6 SP uzup']

In [135]:
x.columns

Index(['L.p.', 'e-mail', 'Klasa', 'Match'], dtype='object')

In [136]:
dbzakladki = pd.read_excel('Uczniowie KNO 2022-2023 - aktualna — kopia.xlsx', sheet_name=None).keys()

In [137]:
dbzakladki= list(dbzakladki)
dbzakladki.sort()
dbzakladki

['1 LO ram',
 '1 LO uzup',
 '1 sp ram',
 '1 sp uzup',
 '2 LO ram',
 '2 LO uzup',
 '2 sp ram',
 '2 sp uzup',
 '3 LO ram',
 '3 LO uzup',
 '3 sp ram',
 '3 sp uzup',
 '4 LO ram',
 '4 LO uzup',
 '4 sp ram',
 '4 sp uzup',
 '5 sp ram',
 '5 sp uzup',
 '6 sp ram',
 '6 sp uzup',
 '7 sp ram',
 '7 sp uzup',
 '8 sp ram',
 '8 sp uzup',
 'Arkusz1',
 'Arkusz2',
 'Podsumowanie',
 'Teams uczniowie ALL',
 'Zespoły w Teams']

In [138]:
dbzakladki = ['1 LO ram',
 '1 LO uzup',
 '1 sp ram',
 '1 sp uzup',
 '2 LO ram',
 '2 LO uzup',
 '2 sp ram',
 '2 sp uzup',
 '3 LO ram',
 '3 LO uzup',
 '3 sp ram',
 '3 sp uzup',
 '4 LO ram',
 '4 LO uzup',
 '4 sp ram',
 '4 sp uzup',
 '5 sp ram',
 '5 sp uzup',
 '6 sp ram',
 '6 sp uzup',
 '7 sp ram',
 '7 sp uzup',
 '8 sp ram',
 '8 sp uzup']

In [139]:
db = pd.concat(pd.read_excel('Uczniowie KNO 2022-2023 - aktualna — kopia.xlsx', usecols='A:L', sheet_name = s).assign(Klasa = s) for s in dbzakladki)

In [140]:
db.columns

Index(['L.p.', 'Nazwisko ucznia', 'Imię ucznia', 'Drugie imię ucznia',
       'nr ksiegi', 'Data urodzenia ucznia', 'Miejsce urodzen..',
       'PESEL ucznia', 'Inny dokument t..', 'Nr i seria doku..',
       'Kraj pobytu ucznia', 'Email', 'Klasa'],
      dtype='object')

In [141]:
db

,L.p.,Nazwisko ucznia,Imię ucznia,Drugie imię ucznia,nr ksiegi,Data urodzenia ucznia,Miejsce urodzen..,PESEL ucznia,Inny dokument t..,Nr i seria doku..,Kraj pobytu ucznia,Email,Klasa
0,1,Staśkiewicz,Anna,Magdalena,4149,2007-12-07 00:00:00,Piła,7320704782,NaN,NaN,Niemcy,alinastaskiewicz@o2.pl,1 LO ram
1,2,Chicińska-Ryster,Nikola,Żaneta,4150,2008-04-14 00:00:00,CHESTERFIELD ENGLAND,8241412527,NaN,NaN,Wielka Brytania,strati-matyja,1 LO ram
2,3,Papież,Kristian,Alan,4151,2007-12-10 00:00:00,Reykjanesbaer - Islandia,NaN,Paszport,ER0669334,Islandia,kristiano2007@gmail.com,1 LO ram
3,4,Kukieła,Amelia,Magdalena,4152,2007-10-30 00:00:00,Bielsko-Biała,7303002809,NaN,NaN,Polska,magda@wp.eu,1 LO ram
4,5,Patacz,Amelia,Michalina,1853,2007-04-16 00:00:00,POLANICA ZDRÓJ,7241601308,Inny dokument ze zdjęciem,CCF287398,Szwecja,edzia1703@o2.pl,1 LO ram
...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,99.0,Włodraczyk,Wiktoria,NaN,4060,2008-04-27 00:00:00,Wałcz,8242702500,NaN,NaN,Turcja,NaN,8 sp uzup
99,100.0,Yalovskyi,Yaroslav,NaN,4061,2008-11-21 00:00:00,Kijów,8312114459,NaN,NaN,Ukraina,juliajalov@gmail.com;fogartu@qulook.com,8 sp uzup
100,101.0,Krawczak,Matthew,Peter,4062,2008-03-04 00:00:00,ST.Thomas,8230413375,NaN,NaN,Kanada,leskrawczak@Gmail.com,8 sp uzup
101,102.0,Lenkiewicz,Zuzanna,NaN,4063,2008-05-09 00:00:00,Londyn,8250912500,NaN,NaN,Wielka Brytania,anka_jak@yahoo.com,8 sp uzup
102,103.0,Radzimiński,Igor,NaN,4624,2009-04-12 00:00:00,Warszawa,9241206590,NaN,NaN,Moskwa,a.radziminska@wp.pl,8 sp uzup

In [142]:
db.dropna(subset=['L.p.'], inplace = True)

In [143]:
db.drop_duplicates(subset=['Nazwisko ucznia', 'Imię ucznia', 'Klasa'], inplace = True)

In [144]:
db

,L.p.,Nazwisko ucznia,Imię ucznia,Drugie imię ucznia,nr ksiegi,Data urodzenia ucznia,Miejsce urodzen..,PESEL ucznia,Inny dokument t..,Nr i seria doku..,Kraj pobytu ucznia,Email,Klasa
0,1,Staśkiewicz,Anna,Magdalena,4149,2007-12-07 00:00:00,Piła,7320704782,NaN,NaN,Niemcy,alinastaskiewicz@o2.pl,1 LO ram
1,2,Chicińska-Ryster,Nikola,Żaneta,4150,2008-04-14 00:00:00,CHESTERFIELD ENGLAND,8241412527,NaN,NaN,Wielka Brytania,strati-matyja,1 LO ram
2,3,Papież,Kristian,Alan,4151,2007-12-10 00:00:00,Reykjanesbaer - Islandia,NaN,Paszport,ER0669334,Islandia,kristiano2007@gmail.com,1 LO ram
3,4,Kukieła,Amelia,Magdalena,4152,2007-10-30 00:00:00,Bielsko-Biała,7303002809,NaN,NaN,Polska,magda@wp.eu,1 LO ram
4,5,Patacz,Amelia,Michalina,1853,2007-04-16 00:00:00,POLANICA ZDRÓJ,7241601308,Inny dokument ze zdjęciem,CCF287398,Szwecja,edzia1703@o2.pl,1 LO ram
...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,99.0,Włodraczyk,Wiktoria,NaN,4060,2008-04-27 00:00:00,Wałcz,8242702500,NaN,NaN,Turcja,NaN,8 sp uzup
99,100.0,Yalovskyi,Yaroslav,NaN,4061,2008-11-21 00:00:00,Kijów,8312114459,NaN,NaN,Ukraina,juliajalov@gmail.com;fogartu@qulook.com,8 sp uzup
100,101.0,Krawczak,Matthew,Peter,4062,2008-03-04 00:00:00,ST.Thomas,8230413375,NaN,NaN,Kanada,leskrawczak@Gmail.com,8 sp uzup
101,102.0,Lenkiewicz,Zuzanna,NaN,4063,2008-05-09 00:00:00,Londyn,8250912500,NaN,NaN,Wielka Brytania,anka_jak@yahoo.com,8 sp uzup
102,103.0,Radzimiński,Igor,NaN,4624,2009-04-12 00:00:00,Warszawa,9241206590,NaN,NaN,Moskwa,a.radziminska@wp.pl,8 sp uzup

In [145]:
db['Data urodzenia ucznia'] = pd.to_datetime(db['Data urodzenia ucznia'], errors='coerce')

C:\Users\WojciechBalcerzak\AppData\Local\Temp\ipykernel_12092\1309943092.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  db['Data urodzenia ucznia'] = pd.to_datetime(db['Data urodzenia ucznia'], errors='coerce')

In [146]:
db.Klasa.unique()

array(['1 LO ram', '1 LO uzup', '1 sp ram', '1 sp uzup', '2 LO ram',
       '2 LO uzup', '2 sp ram', '2 sp uzup', '3 LO ram', '3 LO uzup',
       '3 sp ram', '3 sp uzup', '4 LO ram', '4 LO uzup', '4 sp ram',
       '4 sp uzup', '5 sp ram', '5 sp uzup', '6 sp ram', '6 sp uzup',
       '7 sp ram', '7 sp uzup', '8 sp ram', '8 sp uzup'], dtype=object)

In [147]:
df.columns

Index(['L.p.', 'e-mail', 'Klasa', 'Match'], dtype='object')

In [148]:
df.columns = ['L.p.', 'Nazwisko', 'Imię', 'e-mail', 'Klasa']

ValueError: Length mismatch: Expected axis has 4 elements, new values have 5 elements

In [ ]:
db.columns = ['L.p.', 'Nazwisko', 'Imię', 'Drugie imię',
       'nr_ksiegi', 'Data urodzenia', 'Miejsce ur',
       'PESEL', 'Inny dok', 'Nr i seria',
       'Kraj', 'e-mail', 'Klasa']

In [ ]:
df

In [130]:
df.columns

Index(['L.p.', 'e-mail', 'Klasa', 'Match'], dtype='object')

In [25]:
db.columns

Index(['L.p.', 'Nazwisko', 'Imię', 'Drugie imię', 'nr_ksiegi',
       'Data urodzenia', 'Miejsce ur', 'PESEL', 'Inny dok', 'Nr i seria',
       'Kraj', 'e-mail', 'Klasa'],
      dtype='object')

In [26]:
# d = df.merge(db[['Nazwisko', 'Imię', 'Drugie imię','nr_ksiegi', 'Data urodzenia', 'Miejsce ur','PESEL', 'Klasa']], on=['Nazwisko', 'Imię', 'Klasa'], how = 'left')

In [27]:
#do pominięcia, zbyt złożóny proces
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

# Funkcja do dopasowania nazwisk i klas uczniów
def match_students(row):
    name = row['Nazwisko']
    surname = row['Imię']
    klasa = row['Klasa']
    
    match = process.extractOne(name + ' ' + surname, db['Nazwisko'] + ' ' + db['Imię'], scorer=fuzz.token_sort_ratio)
    
    if match[1] >= 90:  # Prog dopasowania - można dostosować do swoich potrzeb
        matched_row = db.loc[(db['Nazwisko'] + ' ' + db['Imię']) == match[0]]
        if not matched_row.empty and matched_row['Klasa'].iloc[0] == klasa:
            return matched_row.iloc[0]
    
    return pd.Series([None] * len(row.index))

# Dopasowanie uczniów podczas scalania ramki danych
d = df.merge(df.apply(match_students, axis=1), left_index=True, right_index=True, how='left')

# Wyświetlanie scalonych danych
print(d)

    L.p._x      Nazwisko_x         Imię_x  \
1      1.0       Bembnista          Dawid
1      1.0       Bembnista          Dawid
1      1.0       Bembnista          Dawid
1      1.0       Bembnista          Dawid
1      1.0       Bembnista          Dawid
..     ...             ...            ...
186  187.0     Skurczyński        Ariadna
187  188.0        Michalik           Lena
188  189.0       Juniewicz  Julian na ram
189  190.0       Salvetti      Karolina
190  191.0  Schwichtenberg         Arthur

                                  e-mail_x    Klasa_x   0   1   2   3   4  \
1    jolbem1978@gmail.com   tombem30@wp.pl   1 LO ram NaN NaN NaN NaN NaN
1    jolbem1978@gmail.com   tombem30@wp.pl   1 LO ram NaN NaN NaN NaN NaN
1    jolbem1978@gmail.com   tombem30@wp.pl   1 LO ram NaN NaN NaN NaN NaN
1    jolbem1978@gmail.com   tombem30@wp.pl   1 LO ram NaN NaN NaN NaN NaN
1    jolbem1978@gmail.com   tombem30@wp.pl   1 LO ram NaN NaN NaN NaN NaN
..                                     ...        ...  ..  ..  ..  ..  ..
186                paskurczynscy@gmail.com  4 SP uzup NaN NaN NaN NaN NaN
187                          GETEK23@OP.PL  4 SP uzup NaN NaN NaN NaN NaN
188                           FLONTK@O2.PL  4 SP uzup NaN NaN NaN NaN NaN
189               urszulabziuk@qutlook.com  4 SP uzup NaN NaN NaN NaN NaN
190            aleksandragomulak@yahoo.com  4 SP uzup NaN NaN NaN NaN NaN

     ... Inny dok    Klasa_y        Kraj L.p._y         Miejsce ur Nazwisko_y  \
1    ...      NaN   1 LO ram      Włochy   49.0  Nakło Nad Notecią  Bembnista
1    ...      NaN  1 LO uzup       Egipt   24.0              Dubaj    Barakat
1    ...      NaN        NaN         NaN    NaN                NaN        NaN
1    ...      NaN        NaN         NaN    NaN                NaN        NaN
1    ...      NaN   2 LO ram   Hiszpania    7.0        Świebodzice  Bielawski
..   ...      ...        ...         ...    ...                ...        ...
186  ...      NaN        NaN         NaN    NaN                NaN        NaN
187  ...      NaN        NaN         NaN    NaN                NaN        NaN
188  ...      NaN        NaN         NaN    NaN                NaN        NaN
189  ...      NaN        NaN         NaN    NaN                NaN        NaN
190  ...      NaN        NaN         NaN    NaN                NaN        NaN

     Nr i seria       PESEL                  e-mail_y nr_ksiegi
1           NaN  7211200535                       NaN    4184.0
1           NaN  8292013036  basialudwiczak@gmail.com    2213.0
1           NaN         NaN                       NaN       NaN
1           NaN         NaN                       NaN       NaN
1           NaN  6302107270  marta.manager@interia.pl    4192.0
..          ...         ...                       ...       ...
186         NaN         NaN                       NaN       NaN
187         NaN         NaN                       NaN       NaN
188         NaN         NaN                       NaN       NaN
189         NaN         NaN                       NaN       NaN
190         NaN         NaN                       NaN       NaN

[22207 rows x 23 columns]

In [154]:
cc = pd.read_excel('../import_uczniow.xls')

In [155]:
dd = db.loc[db['Klasa'] =='6 sp uzup']

In [156]:
dd

,L.p.,Nazwisko ucznia,Imię ucznia,Drugie imię ucznia,nr ksiegi,Data urodzenia ucznia,Miejsce urodzen..,PESEL ucznia,Inny dokument t..,Nr i seria doku..,Kraj pobytu ucznia,Email,Klasa
0,1.0,Torbeck,Victor,Patrick,3816.0,2010-06-18,Łódź,10261807850,NaN,NaN,Niemcy,monikatorbeck@gmail.com,6 sp uzup
1,2.0,Szczęsny,Fryderyk,NaN,3817.0,2010-10-13,Abu Dhabi,10301311996,NaN,NaN,Zjednoczone Emiraty Arabskie,kasiaszczesna@yahoo.com,6 sp uzup
2,3.0,Zasępa,Marcel,Ryszard,3818.0,2010-06-26,Warszawa,10262608177,NaN,NaN,Hiszpania,w.zasepa@onet.pl,6 sp uzup
3,4.0,Bobek,Miłosz,Łukasz,3819.0,2010-09-07,Chicago,10290713177,NaN,NaN,Stany Zjednoczone,kpbobek@gmail.com,6 sp uzup
4,5.0,Pidek,Ewa,NaN,3820.0,2010-07-09,Belfast,NaN,Paszport,124932384,Wielka Brytania,kasiawujec@hotmail.com,6 sp uzup
...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,134.0,Wojdyło,Filip,NaN,3909.0,2011-11-11,Basingstoke,11311110159,NaN,NaN,Wielka Brytania,NaN,6 sp uzup
135,136.0,Moczulski,Ignacy,Józef,3911.0,2010-05-18,BELGIA,10251813315,NaN,NaN,BELGIA,KGMOCZULSCY@GMAIL.COM,6 sp uzup
136,137.0,Dołkowska,Maja,NaN,3912.0,2010-11-04,HAUGESUND,10310412040,NaN,NaN,NORWEGIA,PAULINA.DOLKOWSKA@HOTMAIL.COM,6 sp uzup
137,138.0,Szafirowska,Emma,Julia,3908.0,2010-12-07,Warszawa,10320708441,NaN,NaN,Francja,anna.szblewska@gmail.com,6 sp uzup
138,139.0,Krajosz,Kajetan,Alan,3981.0,2015-07-18,Świdnik,15271804914,NaN,NaN,Wielka Brytania,krajoszgosia@gmail.com,6 sp uzup

In [157]:
import pandas as pd

# Tworzenie kolumny 'Imię' z uwzględnieniem 'Drugie imię'
dd['Imię'] = dd['Imię'] + ' ' + dd['Drugie imię'].fillna('')

# Wyświetlanie wyników
dd

KeyError: 'Imię'

In [158]:
# Inicjalizujemy pustą ramkę danych z odpowiednimi kolumnami
cd = pd.DataFrame(columns=cc.columns)

# Przypisujemy kolumny z dd do odpowiednich kolumn w cd
cd[['Nr księgi ucznia', 'Imiona', 'Nazwisko', 'Data urodzenia', 'Miejsce urodzenia', 'Pesel', 'e-mail ucznia']] = dd[['nr_ksiegi', 'Imię', 'Nazwisko', 'Data urodzenia', 'Miejsce ur', 'PESEL', 'e-mail']]

# Zostawiamy pozostałe kolumny puste, ponieważ nie mamy dla nich danych w dd

KeyError: "None of [Index(['nr_ksiegi', 'Imię', 'Nazwisko', 'Data urodzenia', 'Miejsce ur',\n       'PESEL', 'e-mail'],\n      dtype='object')] are in the [columns]"

In [92]:
cd.head()

,Nr z dziennika,Imiona,Nazwisko,Płęć,Nr Karty,Nr księgi ucznia,Pesel,Tel Ucznia,e-mail ucznia,Data urodzenia,...,Ulica i nr domu,Kod pocztowy i miejscowość,Województwo,imię i nazwisko matki,numer telefonu do matki,imię i nazwisko ojca,numer telefonu do ojca,email opiekun1,email opiekun 2,uwagi ucznia
0,NaN,David -,Cabrera Wisialski,NaN,NaN,3547,12252307185,NaN,anna.wisialska@gmail.com,2012-04-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Zuzanna Zofia,Cajler,NaN,NaN,3548,12252307185,NaN,kcajler@gmail.com,2012-12-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Emilia Agnieszka,Labenz,NaN,NaN,3549,12252307185,NaN,majalabenz@gmail.com,2012-02-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Szymon Stanisław,Strzyż,NaN,NaN,3550,12252307185,NaN,agalan@wp.pl,2012-11-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Birger Lars,Baranski,NaN,NaN,3551,NaN,NaN,ionie.h@gmail.com,2012-08-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
# Usuwamy '.0' na końcu wartości, konwertujemy na string
cd['Pesel'] = cd['Pesel'].astype(str).str.split('.').str[0]

# Uzupełniamy zera na początku do 11 cyfr
cd['Pesel'] = cd['Pesel'].str.zfill(11)

In [94]:
cd.columns

Index(['Nr z dziennika', 'Imiona', 'Nazwisko', 'Płęć', 'Nr Karty',
       'Nr księgi ucznia', 'Pesel', 'Tel Ucznia', 'e-mail ucznia',
       'Data urodzenia', 'Miejsce urodzenia', 'Miejsce urodzenia miejscownik',
       'Ulica i nr domu', 'Kod pocztowy i miejscowość ', 'Województwo',
       'imię i nazwisko matki', 'numer telefonu do matki',
       'imię i nazwisko ojca', 'numer telefonu do ojca', 'email opiekun1 ',
       'email opiekun 2', 'uwagi ucznia'],
      dtype='object')

In [95]:
df.head()

,L.p.,Nazwisko,Imię,e-mail,Klasa
1,1.0,Bembnista,Dawid,jolbem1978@gmail.com tombem30@wp.pl,1 LO ram
2,2.0,Bryliński,Bogdan,contact@olgabrylinska.com,1 LO ram
3,3.0,Chicińska-Ryster,Nikola,izabela2169@wp.pl,1 LO ram
4,4.0,Ciźla,Nadia,cpn.fit@gmail.com,1 LO ram
5,5.0,Czarnocka,Nikoletta,tamara.c@wp.pl,1 LO ram

In [132]:
c = df.loc[df['Klasa'] == '4 SP uzup']
c

,,L.p.,e-mail,Klasa,Match
Imię,Nazwisko,,,,
Karim,Abdelmouatty,1.0,sahar.hussein2009@yahoo.com,4 SP uzup,"((Karim , Abdelmouatty ), 98)"
Sofiya,Abi Khalil,2.0,pzacharczuk@hotmail.com,4 SP uzup,"((Sofiya , Abi Khalil), 98)"
Ariadna,Andrianopoulou Ziółkowska,3.0,aziolk@gmail.com,4 SP uzup,"((Ariadna , Andrianopoulou Ziółkowska), 99)"
Michał,Andruchów,4.0,agandruchow@yahoo.pl,4 SP uzup,"((Michał , Andruchów), 98)"
Adam,Awdziej,5.0,anna_bogusia@interia.pl,4 SP uzup,"((Adam , Awdziej), 97)"
...,...,...,...,...,...
Ariadna,Skurczyński,187.0,paskurczynscy@gmail.com,4 SP uzup,None
Lena,Michalik,188.0,GETEK23@OP.PL,4 SP uzup,"((Lena , Michalik), 98)"
Julian na ram,Juniewicz,189.0,FLONTK@O2.PL,4 SP uzup,"((Julian Franciszek, Juniewicz), 81)"
Karolina,Salvetti,190.0,urszulabziuk@qutlook.com,4 SP uzup,"((Karolina Rosa, Salvetti ), 92)"
Arthur,Schwichtenberg,191.0,aleksandragomulak@yahoo.com,4 SP uzup,"((Arthur , Schwichtenberg), 98)"

In [120]:
df.set_index(['Imię', 'Nazwisko'], inplace=True)
cd.set_index(['Imiona', 'Nazwisko'], inplace=True)

In [121]:
from fuzzywuzzy import fuzz

def match_names(name, list_names, min_score=0):
    # Start with an empty list of matches
    matches = []

    # For each name in the list, calculate fuzzy matching score
    for name2 in list_names:
        # FuzzyWuzzy returns a ratio given two strings. The closer the ratio is to 100, the smaller the edit distance between the two strings
        score = fuzz.ratio(str(name), str(name2))  # Ensure the names are strings

        # If the score is higher than the minimal score append the match to the matches list
        if (score >= min_score):
            matches.append((name2, score))

    # Sort the matches by score in descending order
    matches = sorted(matches, key=lambda x: x[1], reverse=True)

    # If there are no matches return None
    if len(matches) == 0:
        return None

    # Otherwise return the name and score of the best match
    else:
        return matches[0]

list_names = cd.index.tolist()

# Use the function
df['Match'] = df.index.map(lambda x: match_names(str(x), list_names, min_score=80))  # Ensure the index is a string

In [125]:
cd

,,Nr z dziennika,Płęć,Nr Karty,Nr księgi ucznia,Pesel,Tel Ucznia,e-mail ucznia,Data urodzenia,Miejsce urodzenia,Miejsce urodzenia miejscownik,Ulica i nr domu,Kod pocztowy i miejscowość,Województwo,imię i nazwisko matki,numer telefonu do matki,imię i nazwisko ojca,numer telefonu do ojca,email opiekun1,email opiekun 2,uwagi ucznia
Imiona,Nazwisko,,,,,,,,,,,,,,,,,,,,
David -,Cabrera Wisialski,,m,,3547,12252307185,,anna.wisialska@gmail.com,2012-04-02,Madryt,,,,,,,,,,,
Zuzanna Zofia,Cajler,,k,,3548,12252307185,,kcajler@gmail.com,2012-12-13,Cardiff,,,,,,,,,,,
Emilia Agnieszka,Labenz,,k,,3549,12252307185,,majalabenz@gmail.com,2012-02-25,Kraków,,,,,,,,,,,
Szymon Stanisław,Strzyż,,m,,3550,12252307185,,agalan@wp.pl,2012-11-13,Gdańsk,,,,,,,,,,,
Birger Lars,Baranski,,m,,3551,,,ionie.h@gmail.com,2012-08-11,"Epsom, Wielka Brytania",,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Arthur,Schwichtenberg,,m,,2489,12292113191,,aleksandragomulak@yahoo.com,2012-09-21,Edinburgh,,,,,,,,,,,
Jasper Hari,Wang,,m,,3775,13251808318,,magdalena.przybylska@rocketmail.com,2013-05-18,Huizhou,,,,,,,,,,,
Anastazja,Samojlik,,k,,4110,12281808901,,maksimiuk24@o2.pl; makarynike@wp.pl,2012-08-18,2012-08-18 00:00:00,,,,,,,,,,,
Kacper Wiktor,Rzeszutek,,m,,4092,12321410219,,patka.cefal@poczta.fm; lakiluks19@gmail.com,2012-12-14,,,,,,,,,,,,
Karolina Rosa,Salvetti,,k,,4113,12262111868,,urszulabziuk@qutlook.com;mat.salvetti@gmail.com,2012-06-21,Rovereto,,,,,,,,,,,

In [100]:
cd['Płęć'] = cd['Imiona'].apply(lambda x: 'k' if str(x).strip().endswith('a') else 'm')

In [101]:
cd['Nazwisko'] = cd['Nazwisko'].str.title()
cd['e-mail ucznia'] = cd['e-mail ucznia'].str.strip()
cd

,Nr z dziennika,Imiona,Nazwisko,Płęć,Nr Karty,Nr księgi ucznia,Pesel,Tel Ucznia,e-mail ucznia,Data urodzenia,...,Ulica i nr domu,Kod pocztowy i miejscowość,Województwo,imię i nazwisko matki,numer telefonu do matki,imię i nazwisko ojca,numer telefonu do ojca,email opiekun1,email opiekun 2,uwagi ucznia
0,NaN,David -,Cabrera Wisialski,m,NaN,3547,12252307185,NaN,anna.wisialska@gmail.com,2012-04-02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Zuzanna Zofia,Cajler,k,NaN,3548,12252307185,NaN,kcajler@gmail.com,2012-12-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Emilia Agnieszka,Labenz,k,NaN,3549,12252307185,NaN,majalabenz@gmail.com,2012-02-25,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Szymon Stanisław,Strzyż,m,NaN,3550,12252307185,NaN,agalan@wp.pl,2012-11-13,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Birger Lars,Baranski,m,NaN,3551,00000000nan,NaN,ionie.h@gmail.com,2012-08-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,NaN,Arthur,Schwichtenberg,m,NaN,2489,12292113191,NaN,aleksandragomulak@yahoo.com,2012-09-21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,NaN,Jasper Hari,Wang,m,NaN,3775,13251808318,NaN,magdalena.przybylska@rocketmail.com,2013-05-18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,NaN,Anastazja,Samojlik,k,NaN,4110,12281808901,NaN,maksimiuk24@o2.pl; makarynike@wp.pl,2012-08-18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,NaN,Kacper Wiktor,Rzeszutek,m,NaN,4092,12321410219,NaN,patka.cefal@poczta.fm; lakiluks19@gmail.com,2012-12-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,NaN,Karolina Rosa,Salvetti,k,NaN,4113,12262111868,NaN,urszulabziuk@qutlook.com;mat.salvetti@gmail.com,2012-06-21,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
df['Nazwisko'] = df['Nazwisko'].str.title()
df.head()

,L.p.,Nazwisko,Imię,e-mail,Klasa
1,1.0,Bembnista,Dawid,jolbem1978@gmail.com tombem30@wp.pl,1 LO ram
2,2.0,Bryliński,Bogdan,contact@olgabrylinska.com,1 LO ram
3,3.0,Chicińska-Ryster,Nikola,izabela2169@wp.pl,1 LO ram
4,4.0,Ciźla,Nadia,cpn.fit@gmail.com,1 LO ram
5,5.0,Czarnocka,Nikoletta,tamara.c@wp.pl,1 LO ram

In [103]:
lista_nazwisk = list(df['Nazwisko'])

In [104]:
# lista_nazwisk

In [105]:
cd[~cd['Nazwisko'].isin(lista_nazwisk)]

,Nr z dziennika,Imiona,Nazwisko,Płęć,Nr Karty,Nr księgi ucznia,Pesel,Tel Ucznia,e-mail ucznia,Data urodzenia,...,Ulica i nr domu,Kod pocztowy i miejscowość,Województwo,imię i nazwisko matki,numer telefonu do matki,imię i nazwisko ojca,numer telefonu do ojca,email opiekun1,email opiekun 2,uwagi ucznia
32,NaN,Natalie,Boldbaatar,m,NaN,3572,00000000nan,NaN,joannaboldbaatar@gmail.com,2012-06-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,Martyna Kamila,Krajnik,k,NaN,1953,12242200760,NaN,lukaszkrajnik1983@gmail.com,2012-04-22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,Antoni Jan,Kuśmierczyk,m,NaN,1955,12292605492,NaN,marlen107@wp.pl,2012-09-26,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,NaN,Szymon Igor,Maślanka,m,NaN,1961,12231605336,NaN,ewelinamaslanka76@gmail.com,2012-03-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,NaN,Jan,Sadyś,m,NaN,2371,13212411830,NaN,magdasadys@wp.pl,2013-01-24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,NaN,Oskar,Gąsior,m,NaN,3630,01222221291,NaN,NaN,2012-02-22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,NaN,Gasior,Oskar,m,NaN,3649,01222221291,NaN,NaN,2012-02-22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,NaN,Julia,Szymanska,k,NaN,3556,00000000nan,NaN,NaN,2013-05-10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,NaN,Weronika,Kamińska,k,NaN,3664,13292011847,NaN,EMILIA.KAMINSKA@ONLINE.DE,2013-09-20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,NaN,Oliwier Krystian,Gruca,m,NaN,3665,00000000nan,NaN,jolah21@tlen.pl,2012-08-06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,NaN,Leon Gustaw,Langiewicz,m,NaN,3666,00000000nan,NaN,monika.langiewicz@msz.gov.pl,2012-01-16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,NaN,NaN,Boldbaatar,m,NaN,3668,00000000nan,NaN,batbolor58@yahoo.com,2012-06-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
217,NaN,Anastazja,Samojlik,k,NaN,4110,12281808901,NaN,maksimiuk24@o2.pl; makarynike@wp.pl,2012-08-18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218,NaN,Kacper Wiktor,Rzeszutek,m,NaN,4092,12321410219,NaN,patka.cefal@poczta.fm; lakiluks19@gmail.com,2012-12-14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
cd['Imiona'] = cd['Imiona'].str.title()
cd['Nazwisko'] = cd['Nazwisko'].str.title()

In [108]:
cd['Pesel'] = cd['Pesel'].str.replace('00000000nan', '')
cd.fillna('', inplace = True)
cd['e-mail ucznia'] = cd['e-mail ucznia'].str.strip()
cd

,Nr z dziennika,Imiona,Nazwisko,Płęć,Nr Karty,Nr księgi ucznia,Pesel,Tel Ucznia,e-mail ucznia,Data urodzenia,...,Ulica i nr domu,Kod pocztowy i miejscowość,Województwo,imię i nazwisko matki,numer telefonu do matki,imię i nazwisko ojca,numer telefonu do ojca,email opiekun1,email opiekun 2,uwagi ucznia
0,,David -,Cabrera Wisialski,m,,3547,12252307185,,anna.wisialska@gmail.com,2012-04-02,...,,,,,,,,,,
1,,Zuzanna Zofia,Cajler,k,,3548,12252307185,,kcajler@gmail.com,2012-12-13,...,,,,,,,,,,
2,,Emilia Agnieszka,Labenz,k,,3549,12252307185,,majalabenz@gmail.com,2012-02-25,...,,,,,,,,,,
3,,Szymon Stanisław,Strzyż,m,,3550,12252307185,,agalan@wp.pl,2012-11-13,...,,,,,,,,,,
4,,Birger Lars,Baranski,m,,3551,,,ionie.h@gmail.com,2012-08-11,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,,Arthur,Schwichtenberg,m,,2489,12292113191,,aleksandragomulak@yahoo.com,2012-09-21,...,,,,,,,,,,
216,,Jasper Hari,Wang,m,,3775,13251808318,,magdalena.przybylska@rocketmail.com,2013-05-18,...,,,,,,,,,,
217,,Anastazja,Samojlik,k,,4110,12281808901,,maksimiuk24@o2.pl; makarynike@wp.pl,2012-08-18,...,,,,,,,,,,
218,,Kacper Wiktor,Rzeszutek,m,,4092,12321410219,,patka.cefal@poczta.fm; lakiluks19@gmail.com,2012-12-14,...,,,,,,,,,,
219,,Karolina Rosa,Salvetti,k,,4113,12262111868,,urszulabziuk@qutlook.com;mat.salvetti@gmail.com,2012-06-21,...,,,,,,,,,,

In [118]:
from fuzzywuzzy import fuzz

def match_names(name, list_names, min_score=0):
    # Start with an empty list of matches
    matches = []

    # For each name in the list, calculate fuzzy matching score
    for name2 in list_names:
        # FuzzyWuzzy returns a ratio given two strings. The closer the ratio is to 100, the smaller the edit distance between the two strings
        score = fuzz.ratio(name, name2)

        # If the score is higher than the minimal score append the match to the matches list
        if (score >= min_score):
            matches.append((name2, score))

    # Sort the matches by score in descending order
    matches = sorted(matches, key=lambda x: x[1], reverse=True)

    # If there are no matches return None
    if len(matches) == 0:
        return None

    # Otherwise return the name and score of the best match
    else:
        return matches[0]

list_names = cd.index.tolist()

# Use the function
df['Match'] = df.index.map(lambda x: match_names(x, list_names, min_score=80))

TypeError: object of type 'int' has no len()

In [133]:
cd

,,Nr z dziennika,Płęć,Nr Karty,Nr księgi ucznia,Pesel,Tel Ucznia,e-mail ucznia,Data urodzenia,Miejsce urodzenia,Miejsce urodzenia miejscownik,Ulica i nr domu,Kod pocztowy i miejscowość,Województwo,imię i nazwisko matki,numer telefonu do matki,imię i nazwisko ojca,numer telefonu do ojca,email opiekun1,email opiekun 2,uwagi ucznia
Imiona,Nazwisko,,,,,,,,,,,,,,,,,,,,
David -,Cabrera Wisialski,,m,,3547,12252307185,,anna.wisialska@gmail.com,2012-04-02,Madryt,,,,,,,,,,,
Zuzanna Zofia,Cajler,,k,,3548,12252307185,,kcajler@gmail.com,2012-12-13,Cardiff,,,,,,,,,,,
Emilia Agnieszka,Labenz,,k,,3549,12252307185,,majalabenz@gmail.com,2012-02-25,Kraków,,,,,,,,,,,
Szymon Stanisław,Strzyż,,m,,3550,12252307185,,agalan@wp.pl,2012-11-13,Gdańsk,,,,,,,,,,,
Birger Lars,Baranski,,m,,3551,,,ionie.h@gmail.com,2012-08-11,"Epsom, Wielka Brytania",,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Arthur,Schwichtenberg,,m,,2489,12292113191,,aleksandragomulak@yahoo.com,2012-09-21,Edinburgh,,,,,,,,,,,
Jasper Hari,Wang,,m,,3775,13251808318,,magdalena.przybylska@rocketmail.com,2013-05-18,Huizhou,,,,,,,,,,,
Anastazja,Samojlik,,k,,4110,12281808901,,maksimiuk24@o2.pl; makarynike@wp.pl,2012-08-18,2012-08-18 00:00:00,,,,,,,,,,,
Kacper Wiktor,Rzeszutek,,m,,4092,12321410219,,patka.cefal@poczta.fm; lakiluks19@gmail.com,2012-12-14,,,,,,,,,,,,
Karolina Rosa,Salvetti,,k,,4113,12262111868,,urszulabziuk@qutlook.com;mat.salvetti@gmail.com,2012-06-21,Rovereto,,,,,,,,,,,

In [109]:
cd.drop_duplicates(subset=['Imiona', 'Nazwisko'], inplace = True)

In [111]:
cd.to_csv('klasa4SPuzup.csv', sep = ';', encoding = 'windows-1250', errors='ignore', index=False)